# Generated by Django 3.1.1 on 2020-11-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('resolution', models.CharField(max_length=64)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.cpu')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.display')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.gpu')),
            ],
        ),
        migrations.CreateModel(
            name='NotebookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('descrition', models.CharField(max_length=64)),
                ('typeNotebook', models.CharField(max_length=64)),
                ('series', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=64)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=64)),
                ('star', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserUn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('favorite', models.ManyToManyField(blank=True, related_name='userfavorite', to='notebook.NoteBook')),
            ],
        ),
        migrations.AddField(
            model_name='notebook',
            name='notebookdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebookdata'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.ram'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='rom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.rom'),
        ),
    ]
