# Generated by Django 3.1.1 on 2020-10-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userun',
            name='favarite',
        ),
    ]
