# Generated by Django 3.1.1 on 2020-10-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserUn',
        ),
    ]
