# Generated by Django 3.1.1 on 2020-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_remove_userun_favarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userun',
            name='favarite',
            field=models.ManyToManyField(blank=True, related_name='uerfavarite', to='notebook.NoteBook'),
        ),
    ]
