# Generated by Django 3.1.1 on 2020-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20201121_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='Ostype',
        ),
        migrations.AddField(
            model_name='notebook',
            name='OStype',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notebookdata',
            name='weight',
            field=models.CharField(default='', max_length=64),
        ),
    ]
