# Generated by Django 3.1.1 on 2020-11-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_auto_20201128_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookdata',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notebook/'),
        ),
    ]
